### ISSUE TITLE
How to configure your app for Apache Tomcat 7

### ISSUE THREAD

**Issue by yahyanouali** [ignl/happyfacescrud#1]
Hi,

I really enjoy using your app as it's very structured and works fine, good job.
But I can't configure it to work with Tomcat 7 JDK 1.8 and recent version of spring.
Can you help me pease?

Thanks in advance

Regards, 
Yahya.

**Comment by ignl** [comment]
I didn't use it for a while but lets try. First try to run an app as is on jdk8 and tomcat 7 (should work fine). Then update to newest spring and post its version and error you get.

**Comment by yahyanouali** [comment]
Thanks for your quick response.
I have tried that but I received this exception : 
mars 10, 2018 11:37:46 PM org.apache.tomcat.util.digester.SetPropertiesRule begin
AVERTISSEMENT: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.jee.server:MyTestApp' did not find a matching property.
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server version:        Apache Tomcat/7.0.85
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server built:          Feb 7 2018 18:52:33 UTC
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server number:         7.0.85.0
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: OS Name:               Windows 10
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: OS Version:            10.0
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Architecture:          amd64
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Java Home:             C:\Program Files\Java\jdk1.8.0_161\jre
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: JVM Version:           1.8.0_161-b12
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: JVM Vendor:            Oracle Corporation
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: CATALINA_BASE:         C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: CATALINA_HOME:         C:\Java\apache-tomcat-7.0.85
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dcatalina.base=C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dcatalina.home=C:\Java\apache-tomcat-7.0.85
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dwtp.deploy=C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Djava.endorsed.dirs=C:\Java\apache-tomcat-7.0.85\endorsed
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dfile.encoding=Cp1252
mars 10, 2018 11:37:46 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFOS: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: C:\Program Files\Java\jdk1.8.0_161\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\lessc\;C:\Python363\;C:\Python363\Scripts;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Java\maven\apache-maven-3.5.2\bin;C:\Program Files\Java\jdk1.8.0_161;C:\Program Files\Java\jdk1.8.0_161\bin;C:\Users\iamya\AppData\Local\Programs\Python\Launcher\;C:\Users\iamya\AppData\Local\Microsoft\WindowsApps;C:\Users\iamya\AppData\Roaming\Dashlane\5.2.0.12122\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\iamya\AppData\Roaming\Dashlane\5.2.0.12122\ucrt;C:\geckodriver-v0.19.1-win64;C:\Program Files\cmder;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;;.
mars 10, 2018 11:37:46 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["http-bio-8080"]
mars 10, 2018 11:37:46 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["ajp-bio-8009"]
mars 10, 2018 11:37:46 PM org.apache.catalina.startup.Catalina load
INFOS: Initialization processed in 454 ms
mars 10, 2018 11:37:46 PM org.apache.catalina.core.StandardService startInternal
INFOS: Démarrage du service Catalina
mars 10, 2018 11:37:46 PM org.apache.catalina.core.StandardEngine startInternal
INFOS: Starting Servlet Engine: Apache Tomcat/7.0.85
mars 10, 2018 11:37:48 PM org.apache.catalina.startup.TldConfig execute
INFOS: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
mars 10, 2018 11:37:48 PM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFOS: validateJarFile(C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\MyTestApp\WEB-INF\lib\el-api-2.2.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class
mars 10, 2018 11:37:48 PM org.apache.catalina.deploy.WebXml setVersion
AVERTISSEMENT: Unknown version string [3.1]. Default version will be used.
mars 10, 2018 11:37:51 PM org.apache.catalina.startup.TaglibUriRule body
INFOS: TLD skipped. URI: http://www.springframework.org/tags is already defined
mars 10, 2018 11:37:51 PM org.apache.catalina.startup.TaglibUriRule body
INFOS: TLD skipped. URI: http://www.springframework.org/tags/form is already defined
mars 10, 2018 11:37:51 PM org.apache.catalina.startup.TldConfig execute
INFOS: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
mars 10, 2018 11:37:51 PM org.apache.catalina.core.ApplicationContext log
INFOS: No Spring WebApplicationInitializer types detected on classpath
mars 10, 2018 11:37:51 PM org.apache.catalina.core.ApplicationContext log
INFOS: Set web app root system property: 'webapp.root' = [C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\MyTestApp\]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
mars 10, 2018 11:37:51 PM org.apache.catalina.core.ApplicationContext log
INFOS: Initializing log4j from [C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\MyTestApp\WEB-INF\log4j.xml]
log4j:WARN Continuable parsing error 3 and column 22
log4j:WARN L'élément racine de document "log4j:configuration" doit correspondre à la racine DOCTYPE "null".
log4j:WARN Continuable parsing error 3 and column 22
log4j:WARN Le document nest pas valide : aucune grammaire détectée.
mars 10, 2018 11:37:51 PM org.apache.catalina.core.ApplicationContext log
INFOS: Initializing Spring root WebApplicationContext
mars 10, 2018 11:37:52 PM org.apache.catalina.core.StandardContext listenerStart
GRAVE: Exception lors de l'envoi de l'évènement contexte initialisé (context initialized) à l'instance de classe d'écoute (listener) org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\MyTestApp\WEB-INF\classes\com\test\beans\AccountBean.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\MyTestApp\WEB-INF\classes\com\test\beans\AccountBean.class]; nested exception is java.lang.IllegalArgumentException
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:290)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:242)
	at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:84)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:73)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1438)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1428)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:185)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:139)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:108)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:537)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5641)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [C:\Users\iamya\Documents\jsf_test_Tomcat7\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\MyTestApp\WEB-INF\classes\com\test\beans\AccountBean.class]; nested exception is java.lang.IllegalArgumentException
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:56)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:266)
	... 32 more
Caused by: java.lang.IllegalArgumentException
	at org.springframework.asm.ClassReader.<init>(Unknown Source)
	at org.springframework.asm.ClassReader.<init>(Unknown Source)
	at org.springframework.asm.ClassReader.<init>(Unknown Source)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:53)
	... 35 more

mars 10, 2018 11:37:52 PM com.sun.faces.config.ConfigureListener contextInitialized
INFOS: Initialisation de Mojarra 2.2.7 ( 20140610-1547 https://svn.java.net/svn/mojarra~svn/tags/2.2.7@13362) pour le contexte «/MyTestApp»
mars 10, 2018 11:37:52 PM com.sun.faces.spi.InjectionProviderFactory createInstance
INFOS: JSF1048 : Présence d’annotations PostConstruct/PreDestroy  Les méthodes de beans gérés marquées avec ces annotations auront des annotations dites traitées.
03/10 23:37:52 INFO  alidator.internal.util.Version  - HV000001: Hibernate Validator 5.1.1.Final
mars 10, 2018 11:37:53 PM com.sun.faces.config.ConfigureListener$WebConfigResourceMonitor$Monitor <init>
INFOS: Monitoring jndi:/localhost/MyTestApp/WEB-INF/faces-config.xml for modifications
mars 10, 2018 11:37:53 PM org.primefaces.webapp.PostConstructApplicationEventListener processEvent
INFOS: Running on PrimeFaces 5.0
mars 10, 2018 11:37:53 PM org.omnifaces.VersionLoggerEventListener processEvent
INFOS: Using OmniFaces version 1.7
mars 10, 2018 11:37:53 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: One or more listeners failed to start. Full details will be found in the appropriate container log file
mars 10, 2018 11:37:53 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Erreur de démarrage du contexte [/MyTestApp] suite aux erreurs précédentes
mars 10, 2018 11:37:53 PM org.apache.catalina.core.ApplicationContext log
INFOS: Closing Spring root WebApplicationContext
mars 10, 2018 11:37:53 PM org.apache.catalina.core.StandardContext listenerStop
GRAVE: Exception lors de l'envoi de l'évènement contexte détruit (context destroyed) à l'instance de classe d'écoute org.springframework.web.context.ContextLoaderListener
java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:171)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1090)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1064)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010)
	at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:579)
	at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:115)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5165)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5838)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:149)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

mars 10, 2018 11:37:53 PM org.apache.catalina.core.ApplicationContext log
INFOS: Shutting down log4j
mars 10, 2018 11:37:53 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["http-bio-8080"]
mars 10, 2018 11:37:53 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["ajp-bio-8009"]
mars 10, 2018 11:37:53 PM org.apache.catalina.startup.Catalina start
INFOS: Server startup in 6346 ms

**Comment by yahyanouali** [comment]
I have attached the new modified app

[MyTestApp.zip](https://github.com/ignl/happyfacescrud/files/1800295/MyTestApp.zip)

**Comment by ignl** [comment]
I assume that if you set targetJDK to 1.7 in maven compiler plugin it does work doesnn't it?
I found this issue: https://stackoverflow.com/questions/22526695/java-1-8-asm-classreader-failed-to-parse-class-file-probably-due-to-a-new-java
Project already uses spring 4, but maybe a newer version of spring 4 is needed. Try to clean you local maven repo and update to somewhat newer sping 4 version.

**Comment by ignl** [comment]
Oh I see you have added org.ow2.asm dependency for some reason. 4.0 version seems to be from 2011.

**Comment by yahyanouali** [comment]
No it doesn't work with targetJDK 1.7 and newer version of Spring 4, I think the problem comes from querydsl, but I'm not sure.
I joinded the updated project.
[MyTestApp.zip](https://github.com/ignl/happyfacescrud/files/1800683/MyTestApp.zip)

**Comment by ignl** [comment]
Like I said you have added org.ow2.asm dependency which is old version when jdk8 was not even around. Please use application as it is, then do changes to pom.xml one by one (add dependencies, change jdk version, change lib versions etc). Test after each change and you will know if it broke your app. In this particular case it is most likely org.ow2.asm dependency which was not added in the original app.
